### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by chrisinabztf** [byCrookie/M133#1]
Nur damit wir vom selben sprechen, ich erhalte folgende Fehlermeldung:

`php_1      | [Fri Sep 06 10:53:29.446740 2019] [php7:warn] [pid 16] [client 172.25.0.1:32872] PHP Warning:  file_put_contents(data.json): failed to open stream: Permission denied in /var/www/html/api/api.php on line 30, referer: http://localhost:8001/
`
Das Problem liegt auf der Zeile 30 im File [api.php](ClientSide/app/api/api.php)...hier arbeiten Sie immer noch mit relativen Pfaden im Webverzeichnis drin...da darf man halt keine Files schreiben...

**Comment by byCrookie** [comment]
Das habe ich wohl übersehen. Ich werde es nochmals versuchen, doch bin ich mir fast sicher, auch mit dem /tmp/ schon getestet zu haben. Danke für den Hinweis.

**Comment by byCrookie** [comment]
Läuft nun alles einwandfrei!

**Comment by chrisinabztf** [comment]
Sehr schöne Lösung!
